# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa2cca401f4acb1461cbcac1bccb0dca29d74a96c0ef00e4460a769bde69f41146a8ef1f95cb2537169fdc7bc3e091a6889d8881e72fa8c0a05aa621525ab4e6

test:
  secret_key_base: b64f3cd1a8c408d27682ddb37a7fe3c00f71d7b5457f051655ec7ad2d52321c4663d770ce5652ea577ca11e137d9118e75a87148564ad14472d58abddca693e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
